services:
  backend:
    build:
      context: .
      dockerfile: ./ITS/Dockerfile.dev # Usar Dockerfile de desarrollo
      args:
        RUBY_VERSION: 3.2.2
    volumes:
      - ./ITS:/app # Mapeo directo para desarrollo en caliente
      - bundle_data:/usr/local/bundle
    ports:
      - "3000:3000" # Asegurar el mapeo correcto del puerto
    environment:
      RAILS_ENV: development
      BUNDLE_PATH: /usr/local/bundle
      # REDIS_URL: redis://redis:6379/0
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    # depends_on:
    #   - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev 
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    command: npm run dev

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"

volumes:
  bundle_data:
  node_modules:
